import {ABSTRACT_SCENE} from './abstract-seed-data.js';
import {WORLD_EXPAND_CHARACTERS} from './world-expand-data.js';
import {ROUND4_CHARACTERS,ROUND4_PROGRESSION,ROUND4_QUESTIONS} from './round4-extra.js';
import {MODERN_PRO_QUESTIONS} from './modern-pro-questions.js';
import {SCENE_DATA} from './scene-data.js';
import { rows,DATA } from './data.js';
import { supplementDefinition } from './context.js';
import { SHARED_PACK_CHARACTERS,PACK_PROGRESSION,PACK_QUESTIONS } from './theme-pack-extra.js';
import {supplementStory} from './story-metadata.js';
import {STORY_PROGRESS} from './story-data.js';
const roles=rows('role',`
商店街に来た新人の店員|新人の店員|modern|daily-work|123
地元の道に詳しい配達員|町の配達員|modern|daily-work,journey|1234
図書館の資料整理係|資料係|modern|mystery,daily-work|1234
部活動のまとめ役|部活の仲間|school,modern|buddy|123
卒業を控えた放送部員|放送室|school,modern|reunion,daily-work|1234
祭りの準備を任された職人|祭りの職人|wafu,western|daily-work|123
旅人を迎える宿の管理人|宿の灯り|wafu,western|journey|1234
主君の外出を支える近侍|近侍|wafu,western,fantasy|master-servant|12345
国境の案内をする通訳|国境の声|western,fantasy|journey,status-gap|2345
祭祀の記録を受け継ぐ見習い|祭祀の記録|wafu,fantasy|myth,mystery|2345
精霊と道具を直す修理屋|森の修理屋|fantasy|myth,daily-work|1234
迷宮の出口を調べる測量士|迷宮の地図|fantasy,isekai|journey|12345
異世界で食堂を始めた移住者|二度目の食卓|isekai,fantasy|daily-work|1234
故郷へ帰る道を探す転生者|帰る道|isekai,fantasy|journey,rescue|2345
軌道農園の管理係|星の畑|scifi|daily-work|123
初任務に就く宇宙船の整備士|星船の整備士|scifi|buddy,journey|1234
公開ラボの研究補助員|研究の入口|research,scifi|buddy,daily-work|1234
隔離区域の記録を保管する監査役|監査の記録|research,scifi|mystery|2345
裏社会から離れたい情報屋|最後の情報|underworld,modern|rescue,mystery|345
亡命者を受け入れる診療所の医師|避難所の医師|underworld,modern|rescue|2345
`);
const goals=rows('goal',`
初めての仕事を仲間と完成させたい|初仕事||buddy,daily-work|123
大切な相手へお礼を伝えたい|ありがとう||buddy,romance|123
失くした道具を持ち主へ返したい|返す道具||mystery,daily-work|123
町の祭りを無事に開きたい|祭りの日||buddy,daily-work|123
自分の得意なことを見つけたい|得意の芽||daily-work|123
長年の誤解を解きたい|誤解の向こう||reunion,buddy|1234
旅の景色を手紙で届けたい|旅の便り||journey,reunion|123
昔からの店を次の世代へつなぎたい|店の明日||daily-work,found-family|1234
伝統の道具を今の暮らしでも使えるようにしたい|道具の明日|wafu,western|daily-work|1234
精霊にも読みやすい案内板を作りたい|森の案内板|fantasy|myth,buddy|123
知らない土地で自分の居場所を作りたい|新しい居場所|isekai,fantasy|found-family|1234
星の観測結果を誰でも読める形で残したい|星の記録|scifi,research|daily-work,mystery|1234
仲間が安全に帰れる航路を見つけたい|帰る航路|scifi|journey,rescue|12345
主君の約束を果たしたい|主君の約束|western,wafu,fantasy|master-servant|2345
身分を理由に閉ざされた道を開きたい|開く扉||status-gap|2345
消された記録の真相を知りたい|空白の真相||mystery|2345
組織に追われる相手を逃がしたい|逃がす道|underworld,modern|rescue|345
契約の不公平な条件を変えたい|契約の明日||status-gap|2345
二つの陣営が話せる場所を作りたい|対話の場所||rivalry,buddy|2345
失われた故郷の痕跡を取り戻したい|故郷の痕跡||journey,mystery|2345
`);
const secrets=rows('secret',`
実は料理が得意だが披露する機会がない|内緒のレシピ||daily-work|123
匿名で町の花壇を手入れしている|名もない花壇||daily-work|123
旅に出たふりをして近所で修行していた|近くの修行||reunion,daily-work|123
苦手だと思われている仕事を陰で練習している|内緒の練習||daily-work|123
贈り物を手作りしている途中だ|作りかけの贈り物||romance,buddy|123
昔助けてくれた相手の名前を覚えていない|恩人の名前||reunion,mystery|1234
冷たい返事は手紙の読み違いから始まった|読み違えた便り||reunion,buddy|123
看板の絵を描いた本人なのに名乗れない|看板の描き手||daily-work|123
精霊の言葉が分かるが恥ずかしくて黙っている|森のことば|fantasy|myth|1234
道具に残る古い音を聞くことができる|道具の記憶|fantasy,wafu|myth,mystery|1234
故郷と別の世界の記憶が少し混ざっている|ふたつの記憶|isekai,fantasy|mystery|2345
古い規則を変えたのは自分の提案だった|規則の発案者||daily-work,status-gap|1234
名を伏せて敵側へ手紙を送っている|敵への便り||rivalry,mystery|2345
消された記録の写しを持っている|隠した写し||mystery|2345
主君の命令より先に別の約束を結んでいた|先の約束|wafu,western,fantasy|master-servant,status-gap|2345
自分の身元を示す証書が偽物だ|借りた身元||status-gap,mystery|2345
危険な実験を止める鍵を預かっている|停止の鍵|research,scifi|rescue,mystery|2345
救助信号を発したのは自分だった|信号の主|scifi|rescue,mystery|2345
一族の掟に背いて誰かを匿っている|掟の外|wafu,western|rescue|2345
過去の取引で故郷を危険にさらしたことがある|故郷の負債|underworld,modern|mystery|345
`);
const progression={
deadline:rows('deadline',`
明確な期限なし|それぞれの歩幅|||12345
祭りが始まるまで|祭りの前||daily-work|1234
次の配達日まで|次の便り||daily-work|123
店の開店時間まで|開店の朝||daily-work|123
仲間が旅立つ朝まで|旅立ちの朝||journey,reunion|1234
季節の市が閉じるまで|市の終わり||daily-work|1234
贈り物を渡す記念日まで|記念日||romance,buddy|123
花が咲く季節まで|花の季節||daily-work|1234
共同作業の発表会まで|発表の日||buddy|1234
次の満月まで|満月|fantasy,wafu|myth|12345
峠に雪が積もるまで|雪の峠||journey|1234
宇宙船の出港まで|出港の時|scifi|journey|12345
観測できる星が隠れるまで|星の時間|scifi,research|mystery|1234
異世界へ戻る門が閉じるまで|閉じる門|isekai,fantasy|journey|2345
契約の更新日まで|更新の日||status-gap|2345
次の審問が開かれるまで|審問前夜|western,wafu|mystery|2345
隔離区域が封鎖されるまで|封鎖の時|research,scifi|rescue|2345
追跡者が町へ着くまで|足音||rescue|345
記録が自動削除されるまで|消える記録|scifi,research|mystery|2345
停戦の合意が失効するまで|停戦の終わり||rivalry|2345
`),
obstacle:rows('obstacle',`
仲間の予定がなかなか合わない|予定表||buddy,daily-work|123
道具の使い方を誰も覚えていない|古い道具||daily-work,mystery|123
雨で予定していた道が使えない|雨の道||journey|1234
必要な材料が少し足りない|足りない材料||daily-work|123
言葉が違って相談が通じにくい|ことばの橋||buddy,journey|1234
みんなが遠慮して役割が決まらない|役割の空白||buddy|123
店の場所が分かりにくい|隠れた店||daily-work|123
伝統の方法しか認めない慣習がある|古い慣習||daily-work,status-gap|1234
迷宮の通路が毎朝変わる|変わる通路|fantasy|journey|1234
精霊と人間で時間の感覚が違う|森の時計|fantasy|myth|1234
航路図に古い情報しか残っていない|古い航路|scifi|journey,mystery|1234
発明品の電源が長くもたない|短い充電|scifi,research|daily-work|1234
移動許可を得る手続きが複雑だ|許可の壁||status-gap|2345
情報を独占する仲介者がいる|情報の門番||mystery|2345
敵味方の両方から信用されていない|どちらの側||rivalry|2345
主君の命令が互いに食い違っている|二つの命令|wafu,western,fantasy|master-servant|2345
身分によって入れない区域がある|区画の壁||status-gap|2345
救助に必要な道が監視されている|見張られた道||rescue|345
証拠を管理する組織が公開を拒んでいる|閉ざされた証拠|underworld,research|mystery|345
助けるための装置そのものが故障している|止まった装置|scifi,research|rescue|2345
`),
cost:rows('cost',`
慣れたやり方を変えること|変える勇気||daily-work|1234
一人で完成させるというこだわり|こだわり||buddy|123
休日の予定をひとつ譲ること|譲る休日||daily-work|123
隠してきた苦手を打ち明けること|苦手の告白||buddy|1234
大事にしてきた道具を誰かへ貸すこと|貸す手||daily-work|123
寄り道の時間を減らすこと|道草の時間||journey|123
相手より先に謝ること|先の一言||reunion,buddy|1234
自分の案だけが採用される機会|みんなの案||buddy,daily-work|123
昔の店名を新しい名前へ変えること|店の新しい名||daily-work|1234
引っ越しでいつもの景色を離れること|離れる景色||journey,reunion|1234
秘密の特技を知られること|特技の披露||daily-work|123
信頼を得るまでの時間|信頼の時間||buddy|1234
安全な役職を手放すこと|役職の外||status-gap|2345
組織から与えられた保護|保護の外||rescue|2345
恩人との約束を破る可能性|恩人の約束||master-servant|2345
帰郷する機会を見送ること|帰郷の先||journey|2345
名を残す栄誉を諦めること|名のない仕事||daily-work|2345
敵と協力したという評判を受け入れること|協力の評判||rivalry,buddy|2345
秘密を明かすことで失う居場所|秘密の居場所||mystery|345
二度と戻らない記憶の一部|記憶の欠片|scifi,fantasy|mystery|345
`),
ending:rows('ending',`
日常に小さな楽しみが増える|日々の楽しみ||daily-work|123
互いに頼れる関係になる|頼る手||buddy|123
故郷へ新しい便りを送る|故郷への便り||journey,reunion|123
すれ違いが解けて笑い合う|笑い合う日||reunion,buddy|123
小さな店を一緒に始める|開店の朝||daily-work,buddy|123
失敗を次の挑戦へつなげる|次の挑戦||daily-work|123
それぞれの夢へ進み、交流を続ける|別々の道||buddy,reunion|1234
気まずかった相手と和解する|和解||rivalry,reunion|1234
新しい旅へ出発する|旅のはじまり||journey|1234
受け継ぐ形を変えながら伝統を残す|新しい伝統||daily-work|1234
秘密を分け合い、関係を結び直す|結び直す糸||mystery,buddy|1234
居場所を取り戻して再出発する|再出発||rescue,found-family|1234
真相を明かし、残った課題に向き合う|真相のあと||mystery|234
契約を終え、対等な立場で再会する|契約の先||status-gap,reunion|234
目的は果たすが別々の道を選ぶ|別離||reunion|2345
すべては救えなくても一つの希望を残す|残る灯り||rescue|2345
真相が公になり制度が揺らぎ始める|制度の亀裂||mystery,status-gap|345
救われた者が代償を語り継ぐ|語り継ぐ声||rescue|345
関係は壊れるが秘密だけは守られる|守った秘密||mystery|45
最後の選択で居場所を失う|居場所の果て||rescue|45
`)
};
export const EXTRA_DATA={...DATA,...Object.fromEntries(Object.entries(SCENE_DATA).map(([key,rows])=>[key,[...rows,...ABSTRACT_SCENE[key]]])),...Object.fromEntries(Object.entries(progression).map(([key,pool])=>[key,[...pool.map(item=>supplementDefinition(item,key)),...PACK_PROGRESSION[key]].map(supplementStory).concat(STORY_PROGRESS[key]||[],ROUND4_PROGRESSION[key]||[])])),...Object.fromEntries(['protagonist','counterpart'].flatMap(person=>[['role',roles],['goal',goals],['secret',secrets]].map(([key,pool])=>[`${person}.${key}`,[...pool.map(item=>supplementDefinition(item,key)),...SHARED_PACK_CHARACTERS[key],...ROUND4_CHARACTERS[key],...(WORLD_EXPAND_CHARACTERS[key]||[])].map(supplementStory).map(item=>({...item,id:`${person}-${item.id}`}))])))};
const ORIGINAL_QUESTIONS={
 world:[
 'この世界で当たり前とされることは、どこから来たのだろう。',
 'この制度で得をする人と、困る人は誰だろう。',
 'この世界の便利さには、どんな代償があるだろう。',
 '暮らしの中で大切にされる時間はいつだろう。',
 '食事や移動は、どんな風景になるだろう。',
 'この土地を初めて訪れた人は、何に驚くだろう。',
 '規則から外れる人や場所はあるだろうか。',
 'この世界で貴重とされるものは何だろう。',
 '困ったとき、人々は誰に相談するだろう。',
 'この世界の仕事には、どんな誇りがあるだろう。',
 '場所によって同じ規則の意味が変わることはあるだろうか。',
 '季節や時間によって、暮らしはどう変わるだろう。',
 '外の世界との行き来は、どんなふうに行うだろう。',
 '昔から残るものと、新しく変わったものは何だろう。',
 'この世界の人々が休める場所は、どこだろう。'
 ],
 character:[
 '主人公が欲しいものと、本当に必要なものは同じだろうか。',
 '主人公が一番恐れているのは、どんな変化だろう。',
 '関わる人々が初めて本音を出せるのは、どんな場面だろう。',
 '相手役にも譲れない理由があるとしたら、何だろう。',
 '頼みごとをするとき、どんな言葉を選ぶだろう。',
 '口では否定していても、行動に出る気持ちはあるだろうか。',
 '互いを信じられる根拠は、どんな小さな出来事だろう。',
 '立場が入れ替わったら、相手の何に気づくだろう。',
 '同じ目的を持っていても、方法が違うことはあるだろうか。',
 '関係が始まる前に、どんな生活をしていたのだろう。',
 '言わずに済ませてきた一言は、何だろう。',
 '誰にも見せない場所では、どんな振る舞いをするだろう。',
 '助けられることを受け入れにくい理由はあるだろうか。',
 '相手を誤解している点は、どこだろう。',
 '物語のあとも残しておきたい関係の形は、どんなものだろう。'
 ],
 plot:[
 '事件が起きなかった場合、関係はどうなっていただろう。',
 '目的を果たしたとき、何を手放すことになるだろう。',
 '最初の一歩を踏み出すきっかけは、何だろう。',
 '失敗から新しく分かることは、何だろう。',
 '時間が足りなくなったら、何を先に選ぶだろう。',
 '最後の選択で守るものは、最初と変わっているだろうか。',
 '小さな成功の直後に、どんな課題が見えてくるだろう。',
 '物語の始まりと終わりで、同じ場所の見え方は変わるだろうか。',
 '行動を止めた場合に起きる変化は、何だろう。',
 '誰かの協力が必要になるのは、どの段階だろう。',
 '一度うまくいった方法が使えなくなるのは、いつだろう。',
 'ひねりにつながる予兆を、日常のどこに置けるだろう。',
 '途中で目的を見直す余地はあるだろうか。',
 '読者が次を知りたくなる問いは、何だろう。',
 '結末のあとに残る小さな習慣や景色は、何だろう。'
 ],
 consistency:[
 '秘密が今まで明かされなかった理由は、何だろう。',
 '登場人物が別の手段を選ばない理由は、何だろう。',
 'この出来事を知っている人と、知らない人は誰だろう。',
 'この仕組みを使える条件や限界は、どこにあるだろう。',
 '時間や距離を考えて、移動の順序は成り立つだろうか。',
 '規則に例外があるなら、誰がどう決めるのだろう。',
 '大きな変化のあと、日常にどんな影響が残るだろう。',
 '登場人物の判断に必要な情報は、その時点で届いているだろうか。',
 '語られた過去と現在の行動をつなぐ理由はあるだろうか。',
 '道具や能力が便利すぎるなら、どんな制約を置けるだろう。',
 '約束や契約を破った場合、誰がそれを知るのだろう。',
 'ひねりを知ったあとでも、序盤の描写を読み返せるだろうか。',
 '噂と確かな事実は、文中で区別できているだろうか。',
 '目的と行動が違って見えるなら、その理由をどこで伝えるだろう。',
 '登場人物ができることと、世界の規則はつながっているだろうか。'
 ]
};
// 既存の位置IDはそのまま。追加定義は安定した明示IDを持つ。
export const QUESTION_DATA=Object.fromEntries(Object.entries(ORIGINAL_QUESTIONS).map(([key,pool])=>[key,[...pool,...PACK_QUESTIONS[key],...ROUND4_QUESTIONS[key],...MODERN_PRO_QUESTIONS[key]]]));
