// 明示ID・背景条件を持つ新定義。分類は本文から推定しない。
export const ROUND4_THEMES=[['archive-mystery','記録・記憶・証言の謎','食い違う記録を手がかりに'],['care-gothic','怪異と暮らし・共同ケア','暮らしの隣にある怪異と事情'],['limited-cooperation','期限付き協力・共同契約','共同作業と条件の選び直し'],['practical-skill','職能・暮らしの技で解く','技術と仕事が物語を動かす']];
export const ROUND4_TOPICS=[['record-conflict','記録の不一致'],['mutual-aid','共同ケア'],['negotiation','再交渉'],['craft','職能'],['asymmetric-info','情報差'],['future-record','未来の記録'],['return-home','帰還'],['resource-fairness','資源配分'],['identity-role','身分・役割']];
const split=s=>!s||s==='-'?[]:s.split(',');
export const ROUND4_BASIC=Object.fromEntries(['world','genre','relation','incident','conflict','gimmick','twist'].map(k=>[k,[]]));
// key | slug | text | short | tones | topics | context | stage | extra themes | link | shape
function define(group,lines,defaultStage='modern,fantasy',defaultThemes=[group]){for(const line of lines.trim().split('\n')){const [key,slug,text,titleWord,tones,topics,context='',stage=defaultStage,themes='',link='',shape='pair']=line.split('|');ROUND4_BASIC[key].push({id:`r4-${group}-${key}-${slug}`,text,titleWord,tones:[...tones].map(Number),topicTags:split(topics),plotLinks:split(link),contextTags:split(context),requiresContext:key==='world'?[]:split(context),stageTags:split(stage),themeTags:[...new Set([...defaultThemes,...split(themes)])],source:'generated',origin:'round4',round4Group:group,...(key==='relation'?{relationShape:shape}:{})});}}
define('archive-mystery',`
world|three-clocks|証言の時刻を三種類の時計で記録し、換算係を置く港町|三つの時刻|1234|record-conflict,shop|trade
world|memory-consent|本人が返却を求めるまで記憶の複製を保管する技術がある都市|返却する記憶|234|memory,contract|memory-tech|scifi,research
world|future-library|未来の災害予告を読める装置と、外れた予告の訂正窓口がある町|予告の訂正|234|future-record,record-conflict|future-record|scifi
world|erased-town|戸籍から消された人の記録を隣家が一部ずつ隠し持つ封鎖都市|隣家の戸籍|34|memory,identity-role
genre|testimony|証言の食い違いを仕事の手順から解くミステリー|手順の謎|1234|record-conflict,craft
relation|clock-workers|時刻の換算を教える港の時計師と、証言を集める新人記録係|時計師と記録係|1234|record-conflict,craft|trade
relation|name-choice|古い戸籍を復元したい司書と、旧名で呼ばれることを拒む旅人|復元と改名|234|memory,identity-role
relation|witness-circle|同じ停電を別々の場所で経験し、証言を持ち寄る住人たち|停電の証言者|1234|record-conflict,shared-home|||||group
relation|memory-owner|記憶の複製を返したい保管技師と、複製を見ない権利を求める本人|複製と本人|234|memory,contract|memory-tech|scifi,research
relation|sealed-lovers|互いの記録を開かない約束で再会した元恋人同士|封じた再会|234|memory,relationship-choice||modern,fantasy|romance,reunion
incident|clock-gap|三人の目撃時刻を換算すると、事故の順序が一つだけ入れ替わる|換算後の事故|1234|record-conflict,craft
incident|return-request|保管した記憶の複製へ、本人と別人から同じ返却番号の請求が届く|二つの返却請求|234|memory,identity-role|memory-tech|scifi,research
incident|forecast-appeal|外れた災害予告のため閉店した店が、予告の訂正記録を求める|外れた予告|234|future-record,shop|future-record|scifi
incident|lost-witness|公判前夜、消された住人の存在を示す最後の原簿が焼かれる|焼かれた原簿|45|record-conflict,identity-role
conflict|clock-rule|証言の矛盾を公表したいが、時刻の換算規則自体が間違っていた可能性がある|換算の責任|1234|record-conflict,craft||||r4-clock-rule
conflict|owner-choice|証拠として記憶の複製を保全したいが、保存期限が切れる前に本人の同意を取り直す必要がある|複製の保全期限|234|memory,relationship-choice|memory-tech|scifi,research||r4-owner-choice
conflict|name-ledger|消された名前を公開して存在を証明したいが、新しい名で暮らす人を追跡させてしまう|名前の公開|234|identity-role,memory||||r4-name-ledger
conflict|last-record|家族の記録を守るために、同じ倉庫に残された他人の記録を見捨てるか迫られる|倉庫の選別|45|memory,resource-fairness
gimmick|clock-table|時刻の横に、使った時計の修理日も書き添える証言用紙|修理日付き証言|1234|record-conflict,craft
gimmick|revocable-copy|閲覧許可を撤回すると複製側へ封印をかけられる記憶保存技術|撤回できる複製|234|memory,contract|memory-tech|scifi,research
gimmick|forecast-revision|未来予告と実際の出来事を並べ、差分だけ残す観測装置|予告の差分|234|future-record,record-conflict|future-record|scifi
twist|clock-rule|証言が食い違った日は、時計師が全員に同じ時刻を教える前の移行日だった|移行日の時計|1234|record-conflict,craft||||r4-clock-rule
twist|owner-choice|保存契約の期限は複製の消去日ではなく、第三者が閲覧できる権限を終える日だった|閲覧権の期限|234|memory,contract|memory-tech|scifi,research||r4-owner-choice
twist|name-ledger|原簿の空欄は抹消ではなく、新しい名を本人が決めるまで追跡を止める措置だった|名を待つ空欄|234|identity-role,memory||||r4-name-ledger
`);
define('care-gothic',`
world|shared-stair|住人と階段の精霊が、夜ごとに通れる段数を相談する共同住宅|相談する階段|1234|shared-home,mutual-aid|spirit|fantasy
world|night-laundry|精霊が預かった悲しみを染みに変え、洗濯人へ手当てを頼む街|悲しみの洗濯|1234|shop,mutual-aid|spirit|fantasy
world|shadow-tenancy|家主が亡くなると部屋が住人の影を借りて管理を続ける魔法の街|影の賃貸|234|shared-home,contract|magic|fantasy
world|forgotten-floor|毎年一階分が魔法で消え、住人が引越し先と失われる部屋の記憶を分け合う塔|消える階|345|shared-home,memory|magic|fantasy
genre|household-uncanny|怪異の事情と住人の生活を同じ机で考える生活幻想譚|怪異の生活相談|1234|mutual-aid,shared-home
relation|stair-guide|階段の精霊の声を聞く住人と、引越し荷物を運ぶ配達員|階段の相談役|1234|mutual-aid,shop|spirit|fantasy
relation|laundry-apprentice|触れると昔の悲しみが伝わる布を扱う職人と、手袋を縫う弟子|布と手袋|234|craft,mutual-aid|magic|fantasy
relation|night-shifts|怪異の訪れる時間に合わせて当番を交換する共同住宅の住人たち|夜の当番たち|1234|shared-home,mutual-aid|||||group
relation|shadow-owner|部屋に残る魔法の影と、家主の仕事を引き継ぎたくない遺族|影と遺族|234|memory,identity-role|magic|fantasy
relation|enemy-shelter|互いを追い払いたい怪異の調査員と、怪異を宿して暮らす管理人|追い払えない隣人|234|identity-role,shared-home||fantasy|rivalry
incident|stair-rest|階段の精霊が一晩休みたいと申し出て、上階への配達が止まる|階段の休暇|1234|mutual-aid,shop|spirit|fantasy
incident|borrowed-grief|洗った布から消えた悲しみを、別の持ち主が自分のものだと申し出る|悲しみの持ち主|234|memory,asymmetric-info|magic|fantasy
incident|shadow-rent|家主の魔法の影が、金銭ではなく住人の思い出を家賃として求め始める|思い出の家賃|345|contract,memory|magic|fantasy
incident|floor-goodbye|消える階に一人だけ残ると決めた住人が、最後の食器を隣へ渡す|最後の食器|45|shared-home,relationship-choice|magic|fantasy
conflict|stair-rest|住人の移動を守りたいが、階段の精霊を働かせ続ける約束はできない|階段の休息権|1234|mutual-aid,negotiation|spirit|fantasy||r4-stair-rest
conflict|grief-hands|怪異の残した布を直して返したいが、触れる職人だけが悲しみを引き受けてしまう|修繕する手|234|mutual-aid,craft|magic|fantasy||r4-grief-hands
conflict|shadow-contract|魔法の影を解放したいが、影の消滅と同時に住人の居住権も失われる|影の居住権|2345|contract,shared-home|magic|fantasy||r4-shadow-contract
conflict|floor-memory|塔から逃げる荷物を減らしたいが、失う階の暮らしを示す品を捨てられない|持ち出す暮らし|345|memory,return-home|magic|fantasy
gimmick|shift-bell|住人が鳴らす回数で、精霊に緊急の用事と後回しの用事を伝える呼び鈴|二種類の呼び鈴|1234|mutual-aid,negotiation|spirit|fantasy
gimmick|grief-gloves|布に残る悲しみを一度に受け取らず、縫い目ごとに分ける魔法の手袋|縫い目の手袋|234|craft,mutual-aid|magic|fantasy
gimmick|shadow-signature|家主の死後も効力が続くが、住人が一人ずつ更新を拒める影の契約|影の更新日|234|contract,negotiation|magic|fantasy
twist|stair-rest|精霊が止めていた階段は、誰にも頼めず眠っていた住人へ静けさを届けるためだった|止まる理由|1234|mutual-aid,shared-home|spirit|fantasy||r4-stair-rest
twist|grief-hands|布に残った悲しみは持ち主一人のものではなく、修繕を担った歴代の人々のものだった|縫い手の記憶|234|mutual-aid,memory|magic|fantasy||r4-grief-hands
twist|shadow-contract|契約は影の存在ではなく管理業務の継続を条件にしており、住人が引き継げる余地があった|管理の引継ぎ|234|contract,negotiation|magic|fantasy||r4-shadow-contract
`, 'fantasy');
define('limited-cooperation',`
world|bridge-season|橋が使える一季節だけ、対岸の町と職人を交換する谷|一季節の橋|1234|contract,craft
world|border-desk|国境の両側が閉門まで共同で迷子と落とし物を預かる町|閉門前の窓口|1234|negotiation,shop
world|rotating-command|危機のあいだだけ指揮権を持ち回り、解除日を住人が決める港|持ち回りの指揮|234|identity-role,contract|trade
world|evacuation-pact|沈む街からの退去日まで、敵対地区が輸送路を共有する都市|退去までの協定|345|contract,escape
genre|finite-alliance|別れる日を決めて始める共同事業譚|終わりのある協力|1234|contract,negotiation
relation|border-clerks|閉門時刻の異なる二国の窓口係|対岸の窓口係|1234|negotiation,shop
relation|rival-cooks|祭りの期間だけ同じ調理場を使う競合店の料理人|一週間の厨房|1234|craft,contract
relation|command-circle|一日ごとに指揮役を交代する避難便の乗員たち|交代する指揮役|234|identity-role,caravan|||||group
relation|master-exit|任期満了まで忠誠を求める雇い主と、退任後の自由を確かめる従者|任期付きの忠誠|234|loyalty,contract||fantasy,western|master-servant
relation|lovers-project|共同の仕事が終わっても交際を続けるか、結論を急がない恋人同士|仕事の先の関係|1234|relationship-choice,shop||modern,fantasy|romance
incident|closing-hour|閉門前に受けた相談が両国の担当外となり、引継ぎ先がなくなる|窓口の空白|1234|negotiation,identity-role
incident|kitchen-sign|共有厨房の失敗作が評判になり、どの店の名前で売るか争いになる|失敗作の署名|1234|craft,contract
incident|exit-clause|協力者が退出条項を使う日に、代役を立てない限り出られない但し書きが見つかる|退出の但し書き|234|contract,negotiation
incident|broken-pact|輸送協定が破棄され、救出を約束した人々の一部が取り残される|破棄された航路|45|contract,escape
conflict|closing-hour|担当時間を守りたいが、窓口を閉めれば相談者が境界で一晩待つことになる|閉門と相談|1234|negotiation,mutual-aid||||r4-closing-hour
conflict|shared-name|共同の成果を広めたいが、各自の技術を一つの屋号に吸収されたくない|連名の仕事|1234|craft,identity-role||||r4-shared-name
conflict|exit-clause|仲間に残ってほしいが、自由に離脱できる条件を守らなければ協力が支配になる|離脱できる協力|234|contract,relationship-choice||||r4-exit-clause
conflict|last-order|最後の命令を果たせば故郷へ戻れず、拒めば守ると誓った相手を見捨てる|最後の任務|45|loyalty,return-home||fantasy,western|master-servant
gimmick|handover-ticket|窓口をまたぐたび、相談者ではなく係員が引継ぎ理由を書く相談票|係員の引継ぎ票|1234|negotiation,record-conflict
gimmick|credit-map|完成品のどの部分を誰が作ったか、工程順にたどれる署名図|工程の署名|1234|craft,identity-role
gimmick|sunset-clause|再交渉しなければ自動で権限が消える共同作業の契約|権限の期限|234|contract,negotiation
twist|closing-hour|両国の窓口が閉まる空白時間は、当初は係員同士が相談を引き継ぐ時間として設けられていた|空白の用途|1234|negotiation,identity-role||||r4-closing-hour
twist|shared-name|一つの屋号だと思われた署名は、参加した店の仕事を追える工程図の略記だった|屋号の読み方|1234|craft,identity-role||||r4-shared-name
twist|exit-clause|退出時の代役とは別の人ではなく、残る仕事を終わらせるか縮める共同計画を指していた|退出の再読|234|contract,negotiation||||r4-exit-clause
`);
define('practical-skill',`
world|repair-trail|修理の継ぎ目から品物の旅路を読める職人が集まる宿場|継ぎ目の宿場|1234|craft,caravan|trade
world|recipe-council|保存食の作り方を共有し、災害時の配給を住人が試作して決める町|試作する配給|1234|craft,resource-fairness
world|translation-market|契約の翻訳者が誤訳の訂正履歴を公開する多言語市場|訂正する市場|1234|craft,contract|trade
world|closing-workshop|戦後の道具を兵器へ戻す命令に抗い、最後の工房が閉鎖を待つ街|閉鎖前の工房|34|craft,loyalty
genre|work-solves|暮らしの技を試しながら事件の見方を変える職能群像劇|手を動かす群像|1234|craft,shop
relation|repair-inspector|修理跡から使い方を読む職人と、規格だけで不良と判断する検査員|継ぎ目と規格|1234|craft,record-conflict
relation|cook-carrier|限られた燃料で料理を作る料理人と、食事を冷める前に届けたい配達員|火と配達|1234|craft,resource-fairness
relation|translator-client|契約文を訳し直す通訳と、以前の訳で損をした依頼人|訳し直す相手|234|craft,contract
relation|apprentice-circle|得意な作業を交換し、師匠なしの一日を回す見習いたち|師匠のいない日|1234|craft,mutual-aid|||||group
relation|keeper-traveler|工房に残る責任を持つ職人と、技術を外へ伝えたい旅人|残る手と運ぶ手|234|craft,caravan
incident|repair-direction|壊れた道具の修理跡から、事故当日は普段と逆向きに使われたと分かる|逆向きの道具|1234|craft,record-conflict
incident|meal-count|同じ量の食材なのに、作り方を変えた班だけ配れる食事の数が増える|増えた一食|1234|craft,resource-fairness
incident|translation-right|契約書の古い訳では、依頼人の権利が係員の裁量として書かれていた|訳された権利|234|craft,contract
incident|destroy-tools|工房の技を軍へ渡すことを拒み、弟子たちが唯一の型を壊すか迫られる|最後の型|45|craft,loyalty
conflict|repair-direction|事故の原因を説明したいが、規格外の使い方が働く人を助けていた事実も守りたい|規格外の理由|1234|craft,record-conflict||||r4-repair-direction
conflict|meal-count|食事の数を増やしたいが、一人ひとりが必要な量の違いを無視したくない|同じ数と違う量|1234|craft,resource-fairness||||r4-meal-count
conflict|translation-right|正しい訳を公表したいが、旧訳を信じて結んだ約束が一斉に無効になる|訂正の波紋|234|craft,contract||||r4-translation-right
conflict|skill-cost|技術を残すため協力を求められるが、その成果が大切な相手を傷つける道具になる|残せない技|45|craft,loyalty
gimmick|repair-rubbing|直した箇所を拓本にして、次の職人へ渡す修理履歴|継ぎ目の拓本|1234|craft,memory
gimmick|fuel-board|材料の量だけでなく、調理に使う燃料と待ち時間を並べる献立板|燃料の献立|1234|craft,resource-fairness
gimmick|parallel-translation|訳語の横に、採用しなかった別の意味と理由も残す契約書|選ばなかった訳|234|craft,contract
twist|repair-direction|逆向きの修理は故障を隠すためではなく、片手でも扱えるよう持ち主が頼んだ変更だった|持ち方の依頼|1234|craft,record-conflict||||r4-repair-direction
twist|meal-count|増えた食事は誰かの取り分を減らしたのではなく、再加熱で捨てていた分を作り方で救ったものだった|捨てない一食|1234|craft,resource-fairness||||r4-meal-count
twist|translation-right|原文の権利は全員同じ行動を求めず、それぞれが断る理由を提出できることを保障していた|断るための訳|234|craft,contract||||r4-translation-right
`);
define('cross-beastfolk',`
world|name-office|種族ごとに名前の変わる時期が違い、通称と正式名を並べて扱う国境市|変わる名の市|1234|identity-role,record-conflict|beastfolk,trade|fantasy
world|scent-record|匂いの証言と文字の証言を別々に保管し、照合役が橋渡しする獣人都市|二種類の証言庫|234|interspecies,record-conflict|beastfolk|fantasy
relation|name-translator|他種族の名を文字へ移す通訳と、名前を商標にされた職人|名を取り戻す|234|identity-role,craft|beastfolk,trade|fantasy
relation|witness-team|音・匂い・視覚で別々の手がかりを持つ市場の目撃者たち|違う感覚の証人|1234|interspecies,asymmetric-info|beastfolk,trade|fantasy|||group
incident|renamed-permit|成長で正式名が変わった商人の許可証が、別人のものとして取り上げられる|名と許可証|1234|identity-role,contract|beastfolk,trade|fantasy
incident|scent-weather|決め手とされた匂いの証言が、その日の風向きで別の場所を指すと分かる|風向きの証言|234|record-conflict,interspecies|beastfolk|fantasy
conflict|name-privacy|同一人物だと証明したいが、成長前の名を公開することは本人の禁忌に触れる|古い名の境界|234|identity-role,contract|beastfolk|fantasy
conflict|sense-bias|鋭い感覚の証言を尊重したいが、その種族だけを常に正しい証人にしたくない|感覚と信用|1234|interspecies,record-conflict|beastfolk|fantasy
gimmick|name-chain|旧名を公開せず、本人の同意で同じ人物だと示せる連続署名|伏せた連続署名|1234|identity-role,contract|beastfolk|fantasy
gimmick|weather-sheet|感覚の証言に天候と距離を添え、他種族でも条件を比べられる調書|感覚の条件表|1234|interspecies,craft|beastfolk|fantasy
twist|registered-sound|別人の名だと思われた記録は、本人が聞き取れない音を通訳が省いた結果だった|省かれた音|234|identity-role,record-conflict|beastfolk|fantasy
twist|witness-route|三つの感覚の証言は犯人の居場所ではなく、品物が受け渡された順序を示していた|感覚の順路|1234|interspecies,record-conflict|beastfolk|fantasy
`, 'fantasy',['beastfolk','archive-mystery','practical-skill']);
define('cross-desert',`
world|audit-caravan|隊商が水路の実測図を持ち寄り、宮廷の配水帳簿を照合する砂漠王国|実測図の隊商|1234|water-rights,craft|desert,royal,nomadic,trade|fantasy
world|well-training|井戸を閉じる判断を修理人だけに任せず、各宿場が見習いを送る砂漠の街道|井戸の見習い道|1234|water-rights,mutual-aid|desert,trade|fantasy
relation|auditor-guide|宮廷の水量を監査する帳簿係と、涸れ井戸へ案内する隊商の料理人|帳簿と涸れ井戸|234|water-rights,craft|desert,royal,nomadic|fantasy
relation|map-circle|それぞれ一地点しか測れない道具を持ち寄る宿場の地図師たち|分担する測量|1234|caravan,craft|desert,trade|fantasy|||group
incident|night-measure|昼の配水量は帳簿通りなのに、夜を越すと貯水槽の残量だけが合わない|夜の水量|234|water-rights,record-conflict|desert|fantasy
incident|buried-marker|砂嵐で埋まった測量標を掘り出すと、王国の地図より古い配水線が見つかる|埋もれた測量標|1234|water-rights,memory|desert,royal|fantasy
conflict|audit-exposure|横流しを告発したいが、帳簿にない配水が孤立した宿場を生かしている|帳簿の外の水|234|water-rights,resource-fairness|desert,trade|fantasy
conflict|close-well|崩落の兆候がある井戸を閉じたいが、次の隊商まで住人の水が足りない|閉じる井戸|234|water-rights,craft|desert,nomadic|fantasy
gimmick|paired-measures|宮廷用と宿場用を一組で封印し、差を現地で確かめる水量計|一組の水量計|1234|water-rights,record-conflict|desert,royal|fantasy
gimmick|map-corrections|測った地点と測れなかった地点を別の線で記す隊商地図|測れない線|1234|caravan,craft|desert,nomadic|fantasy
twist|evaporation-order|消えた水は盗難ではなく、宮廷指定の保存容器が夜の冷えで割れた結果だった|容器の命令|234|water-rights,craft|desert,royal|fantasy
twist|old-line|古い配水線は所有権の境界ではなく、井戸を止めた時に互いを支える迂回路だった|水の迂回路|1234|water-rights,mutual-aid|desert|fantasy
`, 'fantasy',['desert-court','practical-skill','limited-cooperation']);
define('cross-scifi',`
world|appeal-ai|公共配分を自律AIが担い、住人が判断理由へ異議を記録できる宇宙港|異議の宇宙港|1234|resource-fairness,record-conflict|artificial-intelligence|scifi
world|personality-copies|人格を複製保存できる技術があり、複製ごとの約束を別々に登録する研究居住区|複製の約束|234|memory,identity-role|memory-tech|scifi,research
relation|ai-disposal|廃棄予定の案内AIと、旧道の名称を聞き取りに来た配達員|旧道の案内役|234|memory,return-home|artificial-intelligence|scifi
relation|copy-dispute|同じ人格記録から生まれ、同じ約束を違う義務として受け止める複製たち|複製たちの義務|234|memory,contract|memory-tech|scifi,research|||group
incident|appeal-class|配給AIへの異議が、同じ分類に入れられた人々へ一度も届いていないと分かる|届かない異議|234|resource-fairness,record-conflict|artificial-intelligence|scifi
incident|future-shutdown|未来観測装置が研究所の閉鎖を予告し、閉鎖前にしか訂正申請を出せないと判明する|閉鎖の予告|34|future-record,contract|future-record|scifi,research
conflict|ai-testimony|案内AIを救うため必要性を示したいが、本人は役に立つことを存続条件にされたくない|必要性の檻|234|identity-role,relationship-choice|artificial-intelligence|scifi
conflict|copy-erasure|複製の一つを消せば全体を復旧できるが、どの複製も別々の人生を歩み始めている|消せない複製|45|memory,identity-role|memory-tech|scifi,research
gimmick|appeal-log|AIの判断を変えた異議だけでなく、却下理由も本人が読める配分記録|却下の記録|1234|resource-fairness,record-conflict|artificial-intelligence|scifi
gimmick|prediction-origin|未来記録がどの観測条件から生まれたか、閲覧時にたどれる装置|予告の出所|234|future-record,craft|future-record|scifi,research
twist|old-road|案内AIが覚えていた旧道名は近道ではなく、立ち退いた住人が互いを探す合言葉だった|旧道の合言葉|234|memory,return-home|artificial-intelligence|scifi
twist|appeal-design|異議が届かなかったのはAIの拒絶ではなく、異議を出す資格から対象者を除いた規則だった|資格の欠落|234|resource-fairness,identity-role|artificial-intelligence|scifi
`, 'scifi',['archive-mystery','limited-cooperation']);
define('cross-journey',`
world|mobile-home|移動拠点の部屋を持ち主でなく当番で引き継ぎ、降りた人の席も残す一行|席を残す拠点|1234|caravan,return-home|nomadic|modern,fantasy
world|return-board|帰還先を地名だけでなく会いたい相手や果たしたい仕事で登録する街道宿|帰る理由の宿|1234|return-home,shop|trade|modern,fantasy
relation|rotating-family|親代わりの役目を交代し、助けを頼む練習もする旅の仲間たち|交代する家族役|1234|mutual-aid,identity-role|nomadic|modern,fantasy|||group
relation|stay-leave|移動拠点に残りたい整備係と、地上で暮らし直したい長年の同僚|拠点と地上|234|return-home,relationship-choice|nomadic|modern,fantasy
incident|role-day|一行の役割を交代した日、帰還先を選ぶ仕事だけが誰にも引き継がれていないと分かる|帰路の担当|1234|identity-role,return-home|nomadic|modern,fantasy
incident|return-closed|長年目指した帰還先が失われ、最後の案内板だけが荷物として届く|帰れない案内板|45|return-home,memory
conflict|seat-left|旅を離れた仲間の席を残したいが、新しく加わる人が座れない|空席の重さ|234|shared-home,relationship-choice|nomadic|modern,fantasy
conflict|role-refusal|家族同然の一行を守りたいが、自分だけが世話役を続けることは断りたい|家族役を降りる|1234|mutual-aid,identity-role|nomadic|modern,fantasy
gimmick|reasons-map|目的地の横に帰りたい理由を記し、理由が変われば道も選び直す旅の地図|帰る理由の地図|1234|return-home,caravan
gimmick|handover-box|一行を降りる人が道具とともに、もう引き受けない役目を書いて残す箱|降りる人の箱|234|identity-role,contract|nomadic|modern,fantasy
twist|empty-seat|空席は戻る義務の印ではなく、立ち寄るだけでも迎えるために残されていた|立ち寄る席|1234|return-home,relationship-choice|nomadic|modern,fantasy
twist|return-reason|一行が同じ町へ帰ると思っていたのは、地名欄にそれぞれ別の帰る理由を書いていたためだった|同じ欄の別の理由|234|return-home,asymmetric-info|nomadic|modern,fantasy
`, 'modern,fantasy',['found-family','journey','limited-cooperation']);
