// 共有人物は28定義。主人公・相手役への展開は新規件数へ二重計上しない。
const rows=(key,source)=>source.trim().split('\n').map(line=>{const [slug,text,titleWord,tones,topics,themes,requires='',stage='',link='']=line.split('|');const split=s=>s?s.split(','):[];return {id:`r4-extra-${key}-${slug}`,text,titleWord,tones:[...tones].map(Number),topicTags:split(topics),themeTags:split(themes),requiresContext:split(requires),contextTags:split(requires),stageTags:split(stage),plotLinks:split(link),source:'generated',origin:'round4-extra'};});
export const ROUND4_CHARACTERS={
role:rows('role',`
clockkeeper|証言に使った時計を直した責任から、時刻の換算を確かめる時計師|時刻を確かめる人|1234|record-conflict,craft|archive-mystery,practical-skill|||r4-clock-rule
names-clerk|旧名を出せない依頼人のため、別の本人確認を探す戸籍係|名を守る係|234|identity-role,craft|archive-mystery,practical-skill
laundry-hand|他人の悲しみを引き受けすぎない方法を弟子と探す洗濯職人|布の手当て役|234|craft,mutual-aid|care-gothic,practical-skill|magic|fantasy|r4-grief-hands
night-caretaker|夜の怪異へ用事を伝えながら、自分の休む日も交渉する管理人|休みを交渉する人|1234|shared-home,negotiation|care-gothic
border-clerk|閉門後の相談を放置しないため対岸へ引継ぎを提案する窓口係|境界の引継ぎ役|1234|negotiation,shop|limited-cooperation|||r4-closing-hour
festival-cook|競合店と一つの厨房を使い、自店だけの味を守ろうとする料理人|共同厨房の料理人|1234|craft,identity-role|limited-cooperation,practical-skill|||r4-shared-name
repair-apprentice|規格外の修理を見つけ、師匠を責める前に使い手へ会いに行く弟子|使い手を訪ねる弟子|1234|craft,record-conflict|practical-skill|||r4-repair-direction
contract-translator|自分の過去の誤訳を訂正し、損をした依頼人へ説明しようとする通訳|誤訳を直す通訳|234|craft,contract|practical-skill,limited-cooperation|||r4-translation-right
water-carrier|配水量の差を料理の実測から示し、監査へ参加する隊商の料理係|量を測る料理係|1234|water-rights,craft|desert-court,practical-skill|desert,nomadic|fantasy
ai-guide|廃棄の日まで旧道名を記録する仕事を自分で選んだ案内AI|旧道を残す案内役|234|memory,identity-role|archive-mystery|artificial-intelligence|scifi
return-traveler|旅の仲間へ帰還先の喪失をまだ告げられず、次の居場所を探す旅人|帰路を探し直す人|345|return-home,asymmetric-info|journey,found-family
ritual-officer|古い祭りの記録と今の参加者の証言を照合し、役割を見直す祭官|役割を確かめる祭官|1234|faith,record-conflict|archive-mystery,limited-cooperation
`),
goal:rows('goal',`
record-choice|復元した記録を公開する前に、名前の出る本人たちの意思を確かめたい|公開前の確認|234|identity-role,memory|archive-mystery|||r4-name-ledger
equal-work|共同の成果を一人の功績にせず、それぞれの仕事が追える形で残したい|仕事の連名|1234|craft,identity-role|practical-skill,limited-cooperation|||r4-shared-name
leave-right|相手を引き留める前に、安心して離脱できる条件を実際に整えたい|離脱を保障する|234|negotiation,contract|limited-cooperation|||r4-exit-clause
rest-turn|怪異も住人も、働けない日に役目を代わってもらえる仕組みを作りたい|休める順番|1234|mutual-aid,shared-home|care-gothic
appeal-access|判断の対象になった全員へ、異議を出す手順を届かせたい|異議の入口|234|resource-fairness,identity-role|limited-cooperation,archive-mystery
skill-handover|自分の技を残したいが、使い道を弟子へ強制せずに渡したい|技の渡し方|234|craft,relationship-choice|practical-skill
chosen-home|同じ場所へ帰れなくても、旅の仲間が会える拠点を一つ残したい|会い直す拠点|234|return-home,caravan|journey,found-family
last-loyalty|最後の任務を終えたあと、命令されずに傍へ残るか自分で選びたい|任務の後の意思|34|loyalty,relationship-choice|master-servant,limited-cooperation
`),
secret:rows('secret',`
wrong-clock|食い違う証言の時刻を換算したのは自分で、規則の変更を伝え忘れていた|伝え忘れた規則|234|record-conflict,craft|archive-mystery|||r4-clock-rule
name-request|消された名前の中に、本人の依頼を受けて自分が伏せたものがある|頼まれた空欄|234|identity-role,memory|archive-mystery|||r4-name-ledger
rest-request|怪異に休みを頼んだのは自分だが、その影響が他の住人に及ぶと知らなかった|休息の依頼主|234|mutual-aid,shared-home|care-gothic
exit-prepared|共同作業の退出手続きを自分のために調べていたが、他の仲間にも必要だと知った|調べていた退出|234|contract,relationship-choice|limited-cooperation|||r4-exit-clause
repair-order|規格外の修理を頼んだのは自分で、理由を職場には隠している|修理の依頼者|234|craft,identity-role|practical-skill|||r4-repair-direction
ration-loss|以前の配給で数だけを合わせ、必要量の多い人を困らせたことがある|数だけの配給|234|resource-fairness,craft|practical-skill|||r4-meal-count
copy-promise|保存された自分の人格複製が、今の自分には守れない約束をしていた|別の自分の約束|34|memory,contract|archive-mystery|memory-tech|scifi,research
return-truth|帰還先がもう存在しないと確かめたが、一行へ伝える言葉を探している|帰還先の真実|345|return-home,asymmetric-info|journey,found-family
`)
};
export const ROUND4_PROGRESSION={
deadline:rows('deadline',`
clock-change|港の時計が新しい換算方式へ切り替わる日まで|時計の切替日|1234|record-conflict,craft|archive-mystery
record-return|預かった原簿を本人へ返す約束の日まで|原簿の返却日|1234|memory,contract|archive-mystery
shift-end|精霊と決めた夜の当番が終わるまで|夜の当番明け|1234|mutual-aid,shared-home|care-gothic|spirit|fantasy
floor-loss|魔法で次の階が消え、部屋へ戻れなくなる朝まで|階が消える朝|345|shared-home,memory|care-gothic|magic|fantasy
bridge-close|対岸へ道具を返せる最後の渡橋時刻まで|最後の渡橋|1234|contract,caravan|limited-cooperation
authority-end|共同指揮の権限が自動で失効する正午まで|権限の正午|234|contract,identity-role|limited-cooperation
test-delivery|修理品の試運転を終えて依頼人へ引き渡す夕方まで|試運転の夕方|1234|craft,shop|practical-skill
last-fuel|残る燃料で食事を作れる最後の一回まで|最後の一回分|345|craft,resource-fairness|practical-skill
`),
obstacle:rows('obstacle',`
different-clock|同じ時刻の表記が、場所によって違う出来事を指している|時刻のずれ|1234|record-conflict|archive-mystery
owner-refusal|記録の持ち主が公開を望まず、正しさだけでは説得できない|公開しない意思|234|memory,relationship-choice|archive-mystery
care-burden|怪異への対応を知る人に、相談も当番も集中している|一人への集中|1234|mutual-aid,shared-home|care-gothic
shadow-price|魔法の影へ頼むたび、住人の大切な思い出が薄れていく|薄れる思い出|345|memory,contract|care-gothic|magic|fantasy
no-owner|共同の仕事なのに、引き継ぐ責任者だけが決まっていない|責任の空席|1234|contract,identity-role|limited-cooperation
unequal-exit|契約上は自由に退出できても、一人だけ住む場所を失う|退出の格差|234|contract,resource-fairness|limited-cooperation
old-standard|使い手に合う修理ほど、検査の古い規格から外れてしまう|古い検査規格|1234|craft,identity-role|practical-skill
fuel-limit|調理の工夫で量は増やせても、運ぶための燃料が足りない|運べない食事|234|craft,resource-fairness|practical-skill
`),
cost:rows('cost',`
record-trust|誤った記録を訂正することで、自分が積み上げた専門家としての信用を失う|訂正する信用|234|craft,record-conflict|archive-mystery,practical-skill
house-memory|住人を逃がす代わりに、消える家で過ごした日々を思い出せなくなる|家の記憶|45|memory,shared-home|care-gothic|magic|fantasy
joint-name|共同作業を解散し、一つの名前で築いた評判を手放す|屋号との別れ|234|identity-role,contract|limited-cooperation
tool-destroyed|技術を兵器に転用させないため、作り直せない型を壊す|壊した型|45|craft,loyalty|practical-skill
return-delay|仲間の退出を支えるため、自分が帰る便を見送る|見送る帰路|234|return-home,mutual-aid|journey,limited-cooperation
loyalty-name|命令より相手の自由を守り、忠臣として呼ばれた名を失う|忠臣の名|345|loyalty,identity-role|master-servant,limited-cooperation
`),
ending:rows('ending',`
record-open|食い違う証言を一つへ消さず、違いを確かめられる形で公開する|違いを残す記録|1234|record-conflict,memory|archive-mystery
name-choice|旧名を公表せずに存在を証明し、新しい名を選ぶ余地が残る|名を選ぶ余地|1234|identity-role,memory|archive-mystery
quiet-house|怪異と住人が別々の休み方を覚え、助けを頼む声だけは届く家になる|声の届く家|1234|shared-home,mutual-aid|care-gothic
house-gone|住人は逃げ延びるが、怪異と暮らした家は二度と現れない|戻らない家|45|shared-home,return-home|care-gothic
contract-end|共同契約は予定通り終わり、残りたい人だけが新しい約束を結ぶ|終えて結ぶ約束|1234|contract,relationship-choice|limited-cooperation
skill-fragments|工房は失われても、弟子たちの違う仕事の中に技の一部ずつが残る|散らばる技|345|craft,memory|practical-skill
`)
};
export const ROUND4_QUESTIONS={
world:[['record-owner','記録の内容を訂正したり公開を止めたりする権利は、誰にあるだろう。','archive-mystery'],['care-system','助ける役目を休みたい人や怪異は、どこへ相談できるだろう。','care-gothic'],['work-right','この世界では、上手にできる人へ仕事が集中したとき誰が調整するだろう。','practical-skill']],
character:[['exit-choice','共同の目標が終わったあと、この人物は誰とどんな距離でいたいだろう。','limited-cooperation'],['skill-limit','得意な技術でも、この人物が引き受けたくない使い道はあるだろう。','practical-skill'],['different-info','互いに知っていることと、知っていても話せないことはどう違うだろう。','archive-mystery']],
plot:[['small-first','大きな事件を解く前に、今回の場面だけで達成できることは何だろう。','limited-cooperation'],['evidence-change','同じ証拠でも、扱う仕事や立場が変わると何が見えるだろう。','archive-mystery'],['rest-turn','休む選択や役目を渡す選択は、次の行動をどう変えるだろう。','care-gothic']],
consistency:[['future-source','予告を使う設定なら、その記録を参照できる仕組みと条件は描かれているだろう。','archive-mystery'],['role-scope','共同契約が終わっても残る権利と、終わる役目を区別できているだろう。','limited-cooperation'],['opening-secret','作者が知る秘密を、登場人物全員が最初から知っている扱いにしていないだろうか。','archive-mystery']]
};
for(const [category,rows] of Object.entries(ROUND4_QUESTIONS))ROUND4_QUESTIONS[category]=rows.map(([slug,text,theme])=>({id:`r4-question-${category}-${slug}`,text,themeTags:[theme],requiresContext:[]}));
