const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({browser,base,out,check})=>{
 async function fresh(fn,{width=390,height=844}={}){const ctx=await browser.newContext({viewport:{width,height},acceptDownloads:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{let seed=578831;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};});await p.goto(base);await p.locator('#summaryBody').filter({hasText:'舞台'}).waitFor();const read=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('creativeIdeaGacha_v2')));try{await fn(p,read);assert.deepEqual(errors,[]);}finally{await ctx.close();}}
 const edit=async(p,key,text,short='編集した短語')=>{const c=p.locator(`[data-key="${key}"]`);await c.getByRole('button',{name:/を編集$/,exact:false}).click();await p.fill(`#input-${key.replaceAll('.','-')}`,text);await p.fill(`#short-${key.replaceAll('.','-')}`,short);return c;};
 const download=async(p,id,name)=>{const pending=p.waitForEvent('download');await p.click(id);const d=await pending;const dest=path.join(out,name);await d.saveAs(dest);return fs.readFileSync(dest,'utf8');};
 const openQuestions=async(p,category)=>{if(!await p.locator('#questionsDetails').evaluate(x=>x.open))await p.locator('#questionsDetails>summary').click();await p.selectOption('#questionCategory',category);await p.click('#rollQuestions');};
 await check('round3 one main draw button and explicit coherence controls preserve current material',()=>fresh(async(p,read)=>{
  assert.equal(await p.locator('#rollDifferent').count(),0);assert.match(await p.locator('#rollAll').textContent(),/固定以外を引く/);assert.equal((await read()).current.settings.coherence,'cohesive');const before=(await read()).current.items;await p.click('[data-coherence="mix"]');assert.equal((await read()).current.settings.coherence,'mix');assert.deepEqual((await read()).current.items,before);await p.click('[data-coherence="cohesive"]');await p.locator('.coherence-control').evaluate(x=>x.scrollIntoView({block:'center'}));await p.screenshot({path:path.join(out,'round3-coherence-mobile.png')});await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,'round3-initial-mobile.png')});
 }));
 await check('round3 save atomically applies fields, background, hidden answers, names, tags and notes',()=>fresh(async(p,read)=>{
  await openQuestions(p,'world');await p.fill('#answer-world-0','住人は道具を貸し合う');await p.selectOption('#questionCategory','character');await p.click('#rollQuestions');await p.fill('#answer-character-1','主人公は旅から戻った職人');await p.selectOption('#questionCategory','plot');
  await edit(p,'world','魔法の工房を住人が共同で使う町','工房の町');await p.check('#context-magic');await p.check('#context-trade');await edit(p,'incident','最後の営業日が決まる','最後の営業日');
  await p.locator('#charactersDetails>summary').click();await p.fill('#protagonistName','楓');await p.fill('#counterpartName','灯');await edit(p,'protagonist.goal','道具の使い方を次の住人へ伝えたい','次の住人');
  await p.fill('#workName','最後の営業日の工房');await p.fill('#workTags','短編、工房');await p.fill('#workNotes','営業が終わっても、道具を貸し合う関係は続く。');const before=(await read()).current;assert.notEqual(before.items.incident.text,'最後の営業日が決まる');await p.screenshot({path:path.join(out,'round3-batch-before-save.png')});await p.click('#saveNew');
  const data=await read(),s=data.works[0].state;assert.equal(data.works.length,1);assert.equal(s.items.incident.text,'最後の営業日が決まる');assert.equal(s.items.incident.titleWord,'最後の営業日');assert.deepEqual(s.items.world.contextTags,['trade','magic']);assert.ok(s.locks.world&&s.locks.incident&&s.locks['protagonist.goal']);assert.equal(s.questions.world[0].answer,'住人は道具を貸し合う');assert.equal(s.questions.character[1].answer,'主人公は旅から戻った職人');assert.ok(s.questions.world[0].locked);assert.equal(s.characters.protagonist.name,'楓');assert.deepEqual(s.metadata.tags,['短編','工房']);assert.match(s.metadata.notes,/道具を貸し合う/);assert.deepEqual(s.texts.titles,before.texts.titles);assert.equal(s.texts.hint,before.texts.hint);assert.match(s.texts.memo,/楓/);
  await p.locator('#saveEditor').evaluate(x=>x.scrollIntoView({block:'start'}));await p.screenshot({path:path.join(out,'round3-batch-saved-mobile.png')});await p.click('#undo');await p.click('#undo');assert.deepEqual((await read()).current,before);assert.equal((await read()).works.length,1);
 }));
 await check('round3 invalid draft prevents partial state, copy and save; correct then save exactly once',()=>fresh(async(p,read)=>{
  const before=(await read()).current;await edit(p,'world','残しておく有効な世界','有効な世界');await p.check('#context-magic');await edit(p,'incident','長'.repeat(501),'長い事件');await p.fill('#workNotes','このメモもまだ部分反映しない');await p.click('#saveNew');assert.deepEqual((await read()).current,before);assert.equal((await read()).works.length,0);assert.equal(await p.evaluate(()=>document.activeElement.id),'input-incident');assert.equal(await p.inputValue('#input-world'),'残しておく有効な世界');assert.equal(await p.isChecked('#context-magic'),true);await p.screenshot({path:path.join(out,'round3-input-error-mobile.png')});
  await p.evaluate(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.copies.push(text)},configurable:true});});await p.locator('[data-copy="summary"]').click();assert.equal(await p.evaluate(()=>window.copies.length),0);assert.deepEqual((await read()).current,before);await p.fill('#input-incident','道具の持ち主が訪ねてくる');await p.click('#saveNew');assert.equal((await read()).works.length,1);assert.equal((await read()).works[0].state.metadata.notes,'このメモもまだ部分反映しない');
 }));
 await check('round3 hidden question error opens its category, focuses and preserves other pending input',()=>fresh(async(p,read)=>{
  await openQuestions(p,'character');await p.fill('#answer-character-2','問'.repeat(2001));await p.selectOption('#questionCategory','world');await p.locator('#questionsDetails>summary').click();await edit(p,'conflict','店と休息の両方を守りたい','店と休息');const before=(await read()).current;await p.click('#saveNew');assert.deepEqual((await read()).current,before);assert.equal(await p.locator('#questionsDetails').evaluate(x=>x.open),true);assert.equal(await p.inputValue('#questionCategory'),'character');assert.equal(await p.evaluate(()=>document.activeElement.id),'answer-character-2');assert.equal(await p.inputValue('#input-conflict'),'店と休息の両方を守りたい');await p.fill('#answer-character-2','休息を学ぶ店主');await p.click('#saveNew');assert.equal((await read()).works[0].state.questions.character[2].answer,'休息を学ぶ店主');
 }));
 await check('round3 individual cancel affects only that editor; current JSON/Markdown and copies apply drafts',()=>fresh(async(p,read)=>{
  const original=(await read()).current.items.world;const world=await edit(p,'world','取り消す世界','取消');await p.check('#context-magic');await edit(p,'incident','町の鐘が修理を頼む','鐘の依頼');await world.getByRole('button',{name:'キャンセル',exact:true}).click();await p.fill('#workNotes','JSONへまとめて含める');const json=JSON.parse(await download(p,'#exportCurrent','round3-current.json'));assert.deepEqual(json.works[0].state.items.world,original);assert.equal(json.works[0].state.items.incident.text,'町の鐘が修理を頼む');assert.equal(json.works[0].state.metadata.notes,'JSONへまとめて含める');
  await edit(p,'conflict','修理したいが休みも取りたい','修理と休み');const md=await download(p,'#downloadMarkdown','round3-current.md');assert.match(md,/修理したいが休みも取りたい/);assert.match(md,/抽選方針：まとまり重視/);
  await p.evaluate(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.copies.push(text)},configurable:true});});
  for(const key of ['summary','memo','hint','titles','markdown']){await p.fill('#workNotes',`コピー経路 ${key}`);const b=p.locator(`[data-copy="${key}"]`);await b.evaluate(x=>{for(let y=x.parentElement;y;y=y.parentElement)if(y.tagName==='DETAILS')y.open=true;});await b.click();const s=(await read()).current,actual=await p.evaluate(()=>window.copies.at(-1));if(key==='markdown')assert.match(actual,/コピー経路 markdown/);else assert.equal(actual,key==='titles'?s.texts.titles.join('\n'):s.texts[key]);assert.equal(s.metadata.notes,`コピー経路 ${key}`);}
 }));
 await check('round3 rebuild and titles apply pending input, unmodified stale editor never becomes custom',()=>fresh(async(p,read)=>{
  await p.locator('[data-key="world"]').getByRole('button',{name:'世界観を編集',exact:true}).click();await p.click('#rollAll');const world=(await read()).current.items.world;await p.click('#saveNew');assert.deepEqual((await read()).current.items.world,world);assert.equal(world.source,'generated');assert.equal((await read()).current.locks.world,false);
  await edit(p,'incident','最後の客へ道具を返す','最後の客');await p.click('#rebuild');assert.equal((await read()).current.items.incident.text,'最後の客へ道具を返す');await edit(p,'conflict','新しい使い手に任せたい','使い手');await p.locator('#rollTitles').evaluate(x=>x.closest('details').open=true);await p.click('#rollTitles');assert.equal((await read()).current.items.conflict.text,'新しい使い手に任せたい');
 }));
 await check('round3 load cancellation preserves drafts; save-before-load uses the same atomic route',()=>fresh(async(p,read)=>{
  await p.fill('#workName','作品A');await p.click('#saveNew');await p.fill('#workName','作品B');await p.click('#saveAs');const works=(await read()).works,aid=works[0].id,bid=works[1].id;await edit(p,'incident','読み込み前に残す事件','残す事件');await p.fill('#workNotes','未反映の読み込み前メモ');const before=(await read()).current;
  const target=p.locator(`[data-action="load"][data-work-id="${aid}"]`);await target.click();await p.locator('#decisionActions').getByRole('button',{name:'キャンセル',exact:true}).click();assert.deepEqual((await read()).current,before);assert.equal(await p.inputValue('#input-incident'),'読み込み前に残す事件');assert.equal(await p.inputValue('#workNotes'),'未反映の読み込み前メモ');await target.click();await p.locator('#decisionActions').getByRole('button',{name:'現在のタネを保存して読み込む'}).click();const after=await read();assert.equal(after.current.loadedWorkId,aid);assert.equal(after.works.find(w=>w.id===bid).state.items.incident.text,'読み込み前に残す事件');assert.equal(after.works.find(w=>w.id===bid).state.metadata.notes,'未反映の読み込み前メモ');
 }));
 await check('round3 quota failure preserves original saved works and exports the applied in-memory state',()=>fresh(async(p,read)=>{
  await p.fill('#workName','容量不足の確認');await p.click('#saveNew');const before=await read();await edit(p,'incident','保存できなくても取り出せる事件','持ち出す事件');await p.fill('#workNotes','メモも手元に残す');await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('quota','QuotaExceededError');};});await p.click('#saveOverwrite');assert.deepEqual((await read()).works,before.works);assert.match(await p.locator('#actionWarning').textContent(),/保存できません/);assert.equal(await p.locator('[data-key="incident"] .field-value').textContent(),'保存できなくても取り出せる事件');const raw=JSON.parse(await download(p,'#exportCurrent','round3-quota-current.json'));assert.equal(raw.works[0].id,before.works[0].id);assert.equal(raw.works[0].state.items.incident.text,'保存できなくても取り出せる事件');assert.equal(raw.works[0].state.metadata.notes,'メモも手元に残す');await p.evaluate(()=>Storage.prototype.setItem=window.originalSet);
 }));
 await check('round3 IME composition and blur do not apply, save or draw; one click after composition saves once',()=>fresh(async(p,read)=>{
  await edit(p,'incident','変換中の日本語','変換');await p.fill('#workName','変換中の作品');const before=(await read()).current;await p.locator('#input-incident').dispatchEvent('compositionstart');await p.locator('#input-incident').focus();await p.keyboard.press('Enter');await p.evaluate(()=>document.querySelector('#saveNew').click());await p.evaluate(()=>document.querySelector('#rollAll').click());assert.equal((await read()).works.length,0);assert.deepEqual((await read()).current,before);await p.locator('#input-incident').dispatchEvent('compositionend');await p.click('#saveNew');assert.equal((await read()).works.length,1);assert.match((await read()).works[0].state.items.incident.text,/変換中の日本語/);
 }));
 await check('round3 backup status tracks five changes; saved-only export remains possible with invalid drafts',()=>fresh(async(p,read)=>{
  for(let i=0;i<5;i++){await p.fill('#workName',`保存作品${i+1}`);await p.click(i?'#saveAs':'#saveNew');}assert.equal(await p.locator('#backupPrompt').isVisible(),true);await p.click('#dismissBackup');await p.fill('#searchWorks','保存');assert.equal(await p.locator('#backupPrompt').isVisible(),false);await p.fill('#searchWorks','');
  assert.match(await p.locator('#backupStatus').textContent(),/まだ書き出していません/);await download(p,'#exportCurrent','round3-before-backup.json');await download(p,'#downloadMarkdown','round3-before-backup.md');assert.match(await p.locator('#backupStatus').textContent(),/まだ書き出していません/);
  await edit(p,'incident','未'.repeat(501),'未保存');await p.fill('#workNotes','保存一覧のJSONには入れない');await p.locator('.backup-panel>summary').click();const raw=JSON.parse(await download(p,'#exportAll','round3-saved-only.json'));assert.equal(raw.works.length,5);assert.ok(raw.works.every(w=>w.state.metadata.notes!=='保存一覧のJSONには入れない'));assert.equal(await p.inputValue('#input-incident'),'未'.repeat(501));assert.match(await p.locator('#backupExportNotice').textContent(),/未保存編集は含みません/);assert.match(await p.locator('#backupStatus').textContent(),/書き出した操作/);await p.locator('.saved-card').first().getByRole('button',{name:/お気に入り/}).click();assert.match(await p.locator('#backupStatus').textContent(),/書き出し後に変更があります/);await p.locator('.backup-status').evaluate(x=>x.scrollIntoView({block:'center'}));await p.screenshot({path:path.join(out,'round3-backup-mobile.png')});
 }));
 await check('round3 backup metadata failure leaves actual work save successful and shows a separate notice',()=>fresh(async(p,read)=>{
  await p.evaluate(()=>{window.nativeSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='creativeIdeaGacha_backupStatus')throw new Error('aux');return window.nativeSet.call(this,k,v);};});await p.fill('#workName','補助表示に失敗しても保存');await p.click('#saveNew');assert.equal((await read()).works.length,1);assert.match(await p.locator('#toast').textContent(),/保存しました/);assert.match(await p.locator('#backupAuxWarning').textContent(),/作品の保存結果とは別/);await p.evaluate(()=>Storage.prototype.setItem=window.nativeSet);
 }));
 await check('round3 old v2 restores mix without regenerating prose; new settings and story tags survive reload',()=>fresh(async(p,read)=>{
  await p.evaluate(()=>{const data=JSON.parse(localStorage.getItem('creativeIdeaGacha_v2'));delete data.current.settings.coherence;for(const row of Object.values(data.current.items))if(row){delete row.topicTags;delete row.plotLinks;}data.current.texts.summary='読み込みで変えない要約';localStorage.setItem('creativeIdeaGacha_v2',JSON.stringify(data));});await p.reload();await p.locator('#summaryBody').filter({hasText:'読み込みで変えない要約'}).waitFor();assert.equal((await read()).current.settings.coherence,'mix');await p.click('[data-coherence="cohesive"]');await p.click('#rollAll');const saved=(await read()).current;await p.reload();await p.locator('#summaryBody').filter({hasText:'舞台'}).waitFor();assert.deepEqual((await read()).current,saved);
 }));
 await check('round3 cozy tone5 offers an explicit tone4 action; group and all-fixed notices remain visible',()=>fresh(async(p,read)=>{
  await p.locator('#themeDetails>summary').click();await p.click('[data-theme="cozy-fantasy"]');await p.selectOption('#toneSelect','5');const before=(await read()).current.items;assert.equal(await p.locator('#cozyToneAction').isVisible(),true);assert.equal((await read()).current.settings.tone,5);await p.click('#cozyToneAction');assert.equal((await read()).current.settings.tone,4);assert.deepEqual((await read()).current.items,before);
  await p.evaluate(async()=>{const {DATA}=await import('./js/data.js');const data=JSON.parse(localStorage.getItem('creativeIdeaGacha_v2'));const def=DATA.relation.find(r=>r.relationShape==='group');const {id,origin,primaryPack,...rest}=def;data.current.items.relation={...rest,candidateId:id};for(const key of ['world','genre','relation','incident','conflict','gimmick','twist'])data.current.locks[key]=true;localStorage.setItem('creativeIdeaGacha_v2',JSON.stringify(data));});await p.reload();await p.locator('#lockStatus').waitFor();await p.click('#rollAll');assert.equal(await p.locator('#rollAll').isEnabled(),true);await p.locator('#charactersDetails>summary').click();assert.match(await p.locator('#groupNotice').textContent(),/集団の中の人物/);assert.equal(await p.locator('#groupNotice').isVisible(),true);
 }));
 await check('round3 mobile focus, small viewports, rotation and dialogs retain usable controls and focus',()=>fresh(async(p)=>{
  for(const width of [360,390,430]){await p.setViewportSize({width,height:844});await p.fill('#workNotes','スマホのメモ');await p.setViewportSize({width,height:390});await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await p.locator('.jump-nav').evaluate(x=>getComputedStyle(x).position),'static');const box=await p.locator('#workNotes').boundingBox();assert.ok(box.y>=0&&box.y+box.height<=390);await p.setViewportSize({width:844,height:width});await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
  await p.setViewportSize({width:390,height:844});await p.fill('#workName','ダイアログ確認');await p.click('#saveNew');const del=p.locator('.saved-card').getByRole('button',{name:'削除',exact:true});await del.click();await p.setViewportSize({width:390,height:300});await p.locator('#decisionActions').getByRole('button',{name:'キャンセル',exact:true}).scrollIntoViewIfNeeded();await p.keyboard.press('Escape');assert.equal(await p.locator('#decisionDialog').evaluate(x=>x.open),false);assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'delete');await p.setViewportSize({width:390,height:844});await openQuestions(p,'world');await p.fill('#answer-world-0','下部の回答欄');await p.setViewportSize({width:390,height:390});await p.waitForTimeout(50);const answer=await p.locator('#answer-world-0').boundingBox();assert.ok(answer.y>=0&&answer.y+answer.height<=390);assert.equal(await p.locator('#rollLight').evaluate(x=>x.getBoundingClientRect().height>=44),true);
 }));
};
