import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {DATA,BASIC,THEMES} from '../js/data.js';import {EXTRA_DATA} from '../js/extra-data.js';import {STAGE_PAIRS,normalizeStages,settingsForPair} from '../js/stage-selection.js';import {STAGE_EXPANSION_ROWS} from '../js/stage-expansion-data.js';import {stageMixData,STAGE_MIX_ROWS} from '../js/stage-mix-data.js';import {mixReport} from '../js/stage-mix.js';import {knownLinks,knownTopics} from '../js/cohesion.js';import {CONTEXTS,worldContext,meetsContext} from '../js/context.js';import {emptyState,updateSettings,rollFields,refreshTexts,clone} from '../js/core.js';import {rollFields as oldRoll,refreshTexts as oldRefresh} from './fixtures/three-pair-core.mjs';import {validateState as oldValidate} from './fixtures/three-pair-storage.mjs';import {validateState,inspectImport,exportJSON,Repository,STORAGE_KEY} from '../js/storage.js';import {NEW_PAIRS,stripExpansion} from './stage-expansion-support.mjs';
const baseline=JSON.parse(fs.readFileSync(new URL('./fixtures/stage-expansion-baseline.json',import.meta.url)));const hash=s=>createHash('sha256').update(s).digest('hex');const rngFor=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);const setting=(pair,tone=3,coherence='cohesive')=>{const s=emptyState();updateSettings(s,{...settingsForPair(pair),tone,coherence});return s;};
test('three new canonical pairs and 36 authored bridge rows have explicit backgrounds, known metadata and exact category allocations',()=>{
 assert.deepEqual(STAGE_PAIRS.slice(3).map(([p])=>p),NEW_PAIRS);assert.equal(STAGE_EXPANSION_ROWS.length,36);assert.equal(STAGE_MIX_ROWS.length,99);assert.equal(new Set(STAGE_MIX_ROWS.map(r=>r.id)).size,99);
 for(const pair of NEW_PAIRS){const rows=STAGE_EXPANSION_ROWS.filter(r=>r.blendPairs.includes(pair));assert.deepEqual(BASIC.map(([key])=>rows.filter(r=>r.key===key).length),[3,1,2,2,2,1,1]);const [a,b]=pair.split('+');assert.deepEqual(normalizeStages(b,a),settingsForPair(pair));for(const row of rows){assert.deepEqual(row.stageTags,[a,b]);assert.deepEqual(row.blendPairs,[pair]);assert.deepEqual(knownTopics(row),row.topicTags);assert.deepEqual(knownLinks(row),row.plotLinks);assert.ok(row.text.length<=500&&row.titleWord.length<=30);assert.ok(row.tones.every(t=>t>=1&&t<=5));assert.ok(row.themeTags.every(t=>THEMES.some(([id])=>t===id)));assert.ok([...row.contextTags,...row.requiresContext].every(t=>CONTEXTS.some(([id])=>t===id)));if(row.key==='world')assert.deepEqual(row.requiresContext,[]);else assert.deepEqual(row.contextTags,[]);}}
});
test('all previous drawing, planner, weights, definitions and storage source stay exact beneath only the pair list/data wiring additions',()=>{
 for(const [file,expected] of Object.entries(baseline.hashes))assert.equal(hash(stripExpansion(file,fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'))),expected,file);
 for(const [saved,original] of [['three-pair-selection.mjs','js/stage-selection.js'],['three-pair-core.mjs','js/core.js'],['three-pair-storage.mjs','js/storage.js'],['three-pair-mix-data.mjs','js/stage-mix-data.js']]){const source=fs.readFileSync(new URL('./fixtures/'+saved,import.meta.url),'utf8').replaceAll("from '../../js/","from './").replaceAll("from './three-pair-selection.mjs'","from './stage-selection.js'").replaceAll("from './three-pair-core.mjs'","from './core.js'").replaceAll("from './three-pair-mix-data.mjs'","from './stage-mix-data.js'");assert.equal(hash(source),baseline.hashes[original],saved);}
 for(const [pair] of STAGE_PAIRS.slice(0,3))assert.equal(Object.values(stageMixData(setting(pair).settings,EXTRA_DATA)).flat().some(r=>STAGE_EXPANSION_ROWS.some(n=>n.id===r.id)),false);
 assert.equal(stageMixData(emptyState().settings,EXTRA_DATA),EXTRA_DATA);assert.equal(Object.values(DATA).flat().some(r=>STAGE_EXPANSION_ROWS.some(n=>n.id===r.id)),false);
});
test('old three pairs preserve exact results, snapshots, recent and RNG across tones and modes with the pre-expansion implementation',()=>{
 for(const [pair] of STAGE_PAIRS.slice(0,3))for(let tone=1;tone<=5;tone++)for(const coherence of ['cohesive','mix']){const a=setting(pair,tone,coherence),b=clone(a),ar={},br={},ra=rngFor(20261007),rb=rngFor(20261007);let ca=0,cb=0;const aa=()=>{ca++;return ra();},bb=()=>{cb++;return rb();};for(let n=0;n<20;n++){assert.deepEqual(rollFields(a,undefined,{data:EXTRA_DATA,recent:ar,rng:aa}),oldRoll(b,undefined,{data:EXTRA_DATA,recent:br,rng:bb}));refreshTexts(a,{rng:aa});oldRefresh(b,{rng:bb});assert.deepEqual(a,b);assert.deepEqual(ar,br);assert.equal(ca,cb);}}
});
test('new pairs at all tones/modes draw 6000 valid cases and record genuine two-stage reports or explicit shortage notices',()=>{
 const matrix=[];for(const pair of NEW_PAIRS)for(let tone=1;tone<=5;tone++)for(const coherence of ['cohesive','mix']){const s=setting(pair,tone,coherence),rng=rngFor(20261007),recent={};let goals=0,noticeCount=0;for(let n=0;n<200;n++){const before=clone(s.items),result=rollFields(s,undefined,{data:EXTRA_DATA,recent,rng});assert.equal(result.changed,7);const report=mixReport(s);if(report.counts.every(c=>c>=2)&&report.bridges>=2)goals++;else if(coherence==='cohesive')assert.ok(result.notices.some(t=>/目標/.test(t)));if(result.notices.length)noticeCount++;for(const [key] of BASIC){const row=s.items[key];assert.ok(meetsContext(row,worldContext(s)));assert.ok(!row.tones.length||row.tones.includes(tone));assert.notEqual(row.candidateId,before[key]?.candidateId);assert.notEqual(row.text,before[key]?.text);if(row.candidateId.startsWith('sm-'))assert.deepEqual(row.blendPairs,[pair]);}assert.equal(s.settings.stage2,pair.split('+')[1]);}matrix.push({pair,tone,coherence,draws:200,goals,percent:goals/2,noticeCount});}
 fs.mkdirSync(new URL('../docs/round6-c/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../docs/round6-c/matrix.json',import.meta.url),JSON.stringify(matrix,null,2)+'\n');
});
test('all 36 bridges are reachable and new v3 JSON roundtrips; old v3 accepts original cases and explicitly refuses new pairs',()=>{
 const compatibility=[];for(const row of STAGE_EXPANSION_ROWS){const s=setting(row.blendPairs[0],row.tones[0]);if(row.key!=='world'){s.items.world={candidateId:null,text:'作者の世界',titleWord:'世界',source:'custom',stageTags:[],themeTags:[],tones:[],contextTags:row.requiresContext,requiresContext:[],topicTags:[],plotLinks:[],blendPairs:[]};s.locks.world=true;}rollFields(s,[row.key],{data:{[row.key]:[row]},rng:()=>0});assert.equal(s.items[row.key].candidateId,row.id);assert.deepEqual(validateState(s),s);assert.deepEqual(inspectImport(exportJSON(s))[0].state,s);}
 for(const [pair] of STAGE_PAIRS){const s=setting(pair);rollFields(s,undefined,{data:EXTRA_DATA,rng:rngFor(7)});refreshTexts(s,{rng:rngFor(1)});assert.deepEqual(inspectImport(exportJSON(s))[0].state,s);if(NEW_PAIRS.includes(pair)){let message='';try{oldValidate(s);}catch(e){message=e.message;}assert.match(message,/対応していません/);compatibility.push({pair,oldAppAccepted:false,message,schemaVersion:s.schemaVersion});}else{assert.deepEqual(oldValidate(s),s);compatibility.push({pair,oldAppAccepted:true,schemaVersion:s.schemaVersion});}
  const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},repo=new Repository(storage);repo.load();const saved=repo.save(s),reloaded=new Repository(storage).load();assert.deepEqual(reloaded.current,saved);assert.ok(map.get(STORAGE_KEY));}
 const single=emptyState();rollFields(single,undefined,{rng:rngFor(6)});assert.deepEqual(oldValidate(single),single);assert.deepEqual(validateState(single),single);
 fs.writeFileSync(new URL('../docs/round6-c/compatibility.json',import.meta.url),JSON.stringify(compatibility,null,2)+'\n');
});
test('unsupported backgrounds and fixed one-sided materials produce honest shortage reports without silently removing a stage',()=>{
 for(const pair of NEW_PAIRS){const s=setting(pair);s.items.world={candidateId:null,text:'作者の背景なしの世界',titleWord:'世界',source:'custom',stageTags:[],themeTags:[],tones:[],contextTags:[],requiresContext:[],topicTags:[],plotLinks:[],blendPairs:[]};s.locks.world=true;for(const [key] of BASIC.slice(1)){s.items[key]={candidateId:null,text:'作者の'+key,titleWord:'素材',source:'custom',stageTags:[],themeTags:[],tones:[],contextTags:[],requiresContext:[],topicTags:[],plotLinks:[],blendPairs:[]};s.locks[key]=true;}rollFields(s,undefined,{data:EXTRA_DATA,rng:rngFor(1)});assert.equal(mixReport(s).status,'片側の素材が少なめ');assert.equal(s.settings.stage2,pair.split('+')[1]);assert.deepEqual(s.items.world.contextTags,[]);}
});
